// entrypoints/content/components/tweet-card.tsx
import { useEffect } from "react";
import {
  extractData,
  TweetData,
} from "@/entrypoints/content/lib/data-analysis.ts";
import ShineBorder from "@/entrypoints/content/components/shine-border.tsx";

interface TweetCardProps {
  element: Element;
}

export function TweetCard({ element }: TweetCardProps) {
  const [tweetData, setTweetData] = useState<TweetData | null>(null);

  useEffect(() => {
    setTimeout(() => {
      const data = extractData(element);
      if (data) {
        setTweetData(data);
      }
    }, 0);
  }, []);

  return (
    <>
      <ShineBorder className="" color={["#A07CFE", "#FE8FB5", "#FFBE7B"]}>
        <div className="css-175oi2r r-18kxxzh r-1wron08 r-onrtq4 r-1awozwy">
          <div className="css-175oi2r" data-testid="Tweet-User-Avatar">
            <div className="css-175oi2r r-18kxxzh r-1wbh5a2 r-13qz1uu">
              <div className="css-175oi2r r-1wbh5a2 r-dnmrzs">
                <div
                  className="css-175oi2r r-bztko3 r-1adg3ll"
                  data-testid="UserAvatar-Container-aheze0"
                  css="width: 40px; height: 40px;"
                >
                  <div
                    className="r-1adg3ll r-13qz1uu"
                    css="padding-bottom: 100%;"
                  ></div>
                  <div className="r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-ipm5af r-13qz1uu">
                    <div className="css-175oi2r r-1adg3ll r-1pi2tsx r-13qz1uu r-45ll9u r-u8s1d r-1v2oles r-176fswd r-bztko3">
                      <div
                        className="r-1adg3ll r-13qz1uu"
                        css="padding-bottom: 100%;"
                      ></div>
                      <div className="r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-ipm5af r-13qz1uu">
                        <div
                          className="css-175oi2r r-sdzlij r-1udh08x r-5f1w11 r-u8s1d r-8jfcpp"
                          css="width: calc(100% + 4px); height: calc(100% + 4px);"
                        >
                          <a
                            href="/aheze0"
                            aria-hidden="true"
                            role="link"
                            tabIndex="-1"
                            className="css-175oi2r r-1pi2tsx r-13qz1uu r-o7ynqc r-6416eg r-1ny4l3l r-1loqt21"
                            css="background-color: rgba(0, 0, 0, 0);"
                          >
                            <div
                              className="css-175oi2r r-sdzlij r-1udh08x r-633pao r-45ll9u r-u8s1d r-1v2oles r-176fswd"
                              css="width: calc(100% - 4px); height: calc(100% - 4px);"
                            >
                              <div
                                className="css-175oi2r r-1pi2tsx r-13qz1uu"
                                css="background-color: rgba(0, 0, 0, 0);"
                              ></div>
                            </div>
                            <div
                              className="css-175oi2r r-sdzlij r-1udh08x r-633pao r-45ll9u r-u8s1d r-1v2oles r-176fswd"
                              css="width: calc(100% - 4px); height: calc(100% - 4px);"
                            >
                              <div className="css-175oi2r r-1pi2tsx r-13qz1uu r-14lw9ot"></div>
                            </div>
                            <div
                              className="css-175oi2r r-sdzlij r-1udh08x r-633pao r-45ll9u r-u8s1d r-1v2oles r-176fswd"
                              css="background-color: rgb(255, 255, 255); width: calc(100% - 4px); height: calc(100% - 4px);"
                            >
                              <div
                                className="css-175oi2r r-1adg3ll r-1udh08x"
                                css="background-color: rgb(185, 202, 211);"
                              >
                                <div
                                  className="r-1adg3ll r-13qz1uu"
                                  css="padding-bottom: 100%;"
                                ></div>
                                <div className="r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-ipm5af r-13qz1uu">
                                  <div className="css-175oi2r r-1mlwlqe r-1udh08x r-417010 r-1p0dtai r-1d2f490 r-u8s1d r-zchlnj r-ipm5af">
                                    <div className="css-175oi2r r-1niwhzg r-vvn4in r-u6sd8q r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-13qz1uu r-1wyyakw r-4gszlv"></div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div
                              className="css-175oi2r r-sdzlij r-1udh08x r-45ll9u r-u8s1d r-1v2oles r-176fswd"
                              css="width: calc(100% - 4px); height: calc(100% - 4px);"
                            >
                              <div className="css-175oi2r r-12181gd r-1pi2tsx r-13qz1uu r-o7ynqc r-6416eg r-1ny4l3l"></div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="css-175oi2r r-1iusvr4 r-16y2uox r-1777fci r-kzbkwu">
          <div className="css-175oi2r r-zl2h9q">
            <div className="css-175oi2r r-k4xj1c r-18u37iz r-1wtj0ep">
              <div className="css-175oi2r r-1d09ksm r-18u37iz r-1wbh5a2">
                <div className="css-175oi2r r-1wbh5a2 r-dnmrzs r-1ny4l3l">
                  <div
                    className="css-175oi2r r-1wbh5a2 r-dnmrzs r-1ny4l3l r-1awozwy r-18u37iz"
                    id="id__mw190std7hh"
                    data-testid="User-Name"
                  >
                    <div className="css-175oi2r r-1awozwy r-18u37iz r-1wbh5a2 r-dnmrzs">
                      <div className="css-175oi2r r-1wbh5a2 r-dnmrzs">
                        <a
                          href="/aheze0"
                          role="link"
                          className="css-175oi2r r-1wbh5a2 r-dnmrzs r-1ny4l3l r-1loqt21"
                        >
                          <div className="css-175oi2r r-1awozwy r-18u37iz r-1wbh5a2 r-dnmrzs">
                            <div
                              dir="ltr"
                              className="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-b88u0q r-1awozwy r-6koalj r-1udh08x r-3s2u2q"
                              css="text-overflow: unset; color: rgb(15, 20, 25);"
                            >
                              <span
                                className="css-1jxf684 r-dnmrzs r-1udh08x r-3s2u2q r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3"
                                css="text-overflow: unset;"
                              >
                                <span
                                  className="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3"
                                  css="text-overflow: unset;"
                                >
                                  Tweet Talk
                                </span>
                              </span>
                            </div>
                            <div
                              dir="ltr"
                              className="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-xoduu5 r-18u37iz r-1q142lx"
                              css="text-overflow: unset; color: rgb(15, 20, 25);"
                            >
                              <span
                                className="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3 r-1awozwy r-xoduu5"
                                css="text-overflow: unset;"
                              >
                                <svg
                                  viewBox="0 0 22 22"
                                  aria-label="Verified account"
                                  role="img"
                                  className="r-4qtqp9 r-yyyyoo r-1xvli5t r-bnwqim r-lrvibr r-m6rgpd r-1cvl2hr r-f9ja8p r-og9te1 r-3t4u6i"
                                  data-testid="icon-verified"
                                >
                                  <g>
                                    <path d="M20.396 11c-.018-.646-.215-1.275-.57-1.816-.354-.54-.852-.972-1.438-1.246.223-.607.27-1.264.14-1.897-.131-.634-.437-1.218-.882-1.687-.47-.445-1.053-.75-1.687-.882-.633-.13-1.29-.083-1.897.14-.273-.587-.704-1.086-1.245-1.44S11.647 1.62 11 1.604c-.646.017-1.273.213-1.813.568s-.969.854-1.24 1.44c-.608-.223-1.267-.272-1.902-.14-.635.13-1.22.436-1.69.882-.445.47-.749 1.055-.878 1.688-.13.633-.08 1.29.144 1.896-.587.274-1.087.705-1.443 1.245-.356.54-.555 1.17-.574 1.817.02.647.218 1.276.574 1.817.356.54.856.972 1.443 1.245-.224.606-.274 1.263-.144 1.896.13.634.433 1.218.877 1.688.47.443 1.054.747 1.687.878.633.132 1.29.084 1.897-.136.274.586.705 1.084 1.246 1.439.54.354 1.17.551 1.816.569.647-.016 1.276-.213 1.817-.567s.972-.854 1.245-1.44c.604.239 1.266.296 1.903.164.636-.132 1.22-.447 1.68-.907.46-.46.776-1.044.908-1.681s.075-1.299-.165-1.903c.586-.274 1.084-.705 1.439-1.246.354-.54.551-1.17.569-1.816zM9.662 14.85l-3.429-3.428 1.293-1.302 2.072 2.072 4.4-4.794 1.347 1.246z"></path>
                                  </g>
                                </svg>
                              </span>
                            </div>
                          </div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="css-175oi2r r-1kkk96v">
                <div className="css-175oi2r r-1awozwy r-18u37iz r-1cmwbt1 r-1wtj0ep">
                  <div className="css-175oi2r r-1awozwy r-6koalj r-18u37iz">
                    <div className="css-175oi2r">
                      <div className="css-175oi2r r-18u37iz r-1h0z5md">
                        <button
                          aria-expanded="false"
                          aria-haspopup="menu"
                          aria-label="More"
                          role="button"
                          className="css-175oi2r r-1777fci r-bt1l66 r-bztko3 r-lrvibr r-1loqt21 r-1ny4l3l"
                          data-testid="caret"
                          type="button"
                        >
                          <div
                            dir="ltr"
                            className="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-1awozwy r-6koalj r-1h0z5md r-o7ynqc r-clp7b1 r-3s2u2q"
                            css="text-overflow: unset; color: rgb(83, 100, 113);"
                          >
                            <div className="css-175oi2r r-xoduu5">
                              <div className="css-175oi2r r-xoduu5 r-1p0dtai r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-1niwhzg r-sdzlij r-xf4iuw r-o7ynqc r-6416eg r-1ny4l3l"></div>
                              <svg
                                viewBox="0 0 24 24"
                                aria-hidden="true"
                                className="r-4qtqp9 r-yyyyoo r-dnmrzs r-bnwqim r-lrvibr r-m6rgpd r-1xvli5t r-1hdv0qi"
                              >
                                <g>
                                  <path d="M3 12c0-1.1.9-2 2-2s2 .9 2 2-.9 2-2 2-2-.9-2-2zm9 2c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm7 0c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2z"></path>
                                </g>
                              </svg>
                            </div>
                          </div>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="css-175oi2r">
            <div
              dir="auto"
              lang="en"
              className="css-146c3p1 r-8akbws r-krxsd3 r-dnmrzs r-1udh08x r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-bnwqim"
              id="id__ve9cyjuwti"
              data-testid="tweetText"
              css="-webkit-line-clamp: 10; text-overflow: unset; color: rgb(15, 20, 25);"
            >
              <span
                className="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3"
                css="text-overflow: unset;"
              >
                就你会刷 Twitter ？
              </span>
            </div>
          </div>
        </div>
      </ShineBorder>
    </>
  );
}

// entrypoints/content/components/tweet-card.vue
<script setup lang="ts">

</script>

<template>
  <div class="css-175oi2r r-18kxxzh r-1wron08 r-onrtq4 r-1awozwy">
    <div class="css-175oi2r" data-testid="Tweet-User-Avatar">
      <div class="css-175oi2r r-18kxxzh r-1wbh5a2 r-13qz1uu">
        <div class="css-175oi2r r-1wbh5a2 r-dnmrzs">
          <div class="css-175oi2r r-bztko3 r-1adg3ll" data-testid="UserAvatar-Container-aheze0"
               style="width: 40px; height: 40px;">
            <div class="r-1adg3ll r-13qz1uu" style="padding-bottom: 100%;"></div>
            <div class="r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-ipm5af r-13qz1uu">
              <div class="css-175oi2r r-1adg3ll r-1pi2tsx r-13qz1uu r-45ll9u r-u8s1d r-1v2oles r-176fswd r-bztko3">
                <div class="r-1adg3ll r-13qz1uu" style="padding-bottom: 100%;"></div>
                <div class="r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-ipm5af r-13qz1uu">
                  <div class="css-175oi2r r-sdzlij r-1udh08x r-5f1w11 r-u8s1d r-8jfcpp"
                       style="width: calc(100% + 4px); height: calc(100% + 4px);"><a href="/aheze0" aria-hidden="true"
                                                                                     role="link" tabindex="-1"
                                                                                     class="css-175oi2r r-1pi2tsx r-13qz1uu r-o7ynqc r-6416eg r-1ny4l3l r-1loqt21"
                                                                                     style="background-color: rgba(0, 0, 0, 0);">
                    <div class="css-175oi2r r-sdzlij r-1udh08x r-633pao r-45ll9u r-u8s1d r-1v2oles r-176fswd"
                         style="width: calc(100% - 4px); height: calc(100% - 4px);">
                      <div class="css-175oi2r r-1pi2tsx r-13qz1uu" style="background-color: rgba(0, 0, 0, 0);"></div>
                    </div>
                    <div class="css-175oi2r r-sdzlij r-1udh08x r-633pao r-45ll9u r-u8s1d r-1v2oles r-176fswd"
                         style="width: calc(100% - 4px); height: calc(100% - 4px);">
                      <div class="css-175oi2r r-1pi2tsx r-13qz1uu r-14lw9ot"></div>
                    </div>
                    <div class="css-175oi2r r-sdzlij r-1udh08x r-633pao r-45ll9u r-u8s1d r-1v2oles r-176fswd"
                         style="background-color: rgb(255, 255, 255); width: calc(100% - 4px); height: calc(100% - 4px);">
                      <div class="css-175oi2r r-1adg3ll r-1udh08x" style="background-color: rgb(185, 202, 211);">
                        <div class="r-1adg3ll r-13qz1uu" style="padding-bottom: 100%;"></div>
                        <div class="r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-ipm5af r-13qz1uu">
                          <div
                              class="css-175oi2r r-1mlwlqe r-1udh08x r-417010 r-1p0dtai r-1d2f490 r-u8s1d r-zchlnj r-ipm5af">
                            <div
                                class="css-175oi2r r-1niwhzg r-vvn4in r-u6sd8q r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-13qz1uu r-1wyyakw r-4gszlv"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="css-175oi2r r-sdzlij r-1udh08x r-45ll9u r-u8s1d r-1v2oles r-176fswd"
                         style="width: calc(100% - 4px); height: calc(100% - 4px);">
                      <div class="css-175oi2r r-12181gd r-1pi2tsx r-13qz1uu r-o7ynqc r-6416eg r-1ny4l3l"></div>
                    </div>
                  </a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="css-175oi2r r-1iusvr4 r-16y2uox r-1777fci r-kzbkwu">
    <div class="css-175oi2r r-zl2h9q">
      <div class="css-175oi2r r-k4xj1c r-18u37iz r-1wtj0ep">
        <div class="css-175oi2r r-1d09ksm r-18u37iz r-1wbh5a2">
          <div class="css-175oi2r r-1wbh5a2 r-dnmrzs r-1ny4l3l">
            <div class="css-175oi2r r-1wbh5a2 r-dnmrzs r-1ny4l3l r-1awozwy r-18u37iz" id="id__mw190std7hh"
                 data-testid="User-Name">
              <div class="css-175oi2r r-1awozwy r-18u37iz r-1wbh5a2 r-dnmrzs">
                <div class="css-175oi2r r-1wbh5a2 r-dnmrzs"><a href="/aheze0" role="link"
                                                               class="css-175oi2r r-1wbh5a2 r-dnmrzs r-1ny4l3l r-1loqt21">
                  <div class="css-175oi2r r-1awozwy r-18u37iz r-1wbh5a2 r-dnmrzs">
                    <div dir="ltr"
                         class="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-b88u0q r-1awozwy r-6koalj r-1udh08x r-3s2u2q"
                         style="text-overflow: unset; color: rgb(15, 20, 25);"><span
                        class="css-1jxf684 r-dnmrzs r-1udh08x r-3s2u2q r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3"
                        style="text-overflow: unset;"><span class="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3"
                                                            style="text-overflow: unset;">Tweet Talk</span></span>
                    </div>
                    <div dir="ltr"
                         class="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-xoduu5 r-18u37iz r-1q142lx"
                         style="text-overflow: unset; color: rgb(15, 20, 25);"><span
                        class="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3 r-1awozwy r-xoduu5"
                        style="text-overflow: unset;"><svg viewBox="0 0 22 22" aria-label="Verified account"
                                                           role="img"
                                                           class="r-4qtqp9 r-yyyyoo r-1xvli5t r-bnwqim r-lrvibr r-m6rgpd r-1cvl2hr r-f9ja8p r-og9te1 r-3t4u6i"
                                                           data-testid="icon-verified"><g><path
                        d="M20.396 11c-.018-.646-.215-1.275-.57-1.816-.354-.54-.852-.972-1.438-1.246.223-.607.27-1.264.14-1.897-.131-.634-.437-1.218-.882-1.687-.47-.445-1.053-.75-1.687-.882-.633-.13-1.29-.083-1.897.14-.273-.587-.704-1.086-1.245-1.44S11.647 1.62 11 1.604c-.646.017-1.273.213-1.813.568s-.969.854-1.24 1.44c-.608-.223-1.267-.272-1.902-.14-.635.13-1.22.436-1.69.882-.445.47-.749 1.055-.878 1.688-.13.633-.08 1.29.144 1.896-.587.274-1.087.705-1.443 1.245-.356.54-.555 1.17-.574 1.817.02.647.218 1.276.574 1.817.356.54.856.972 1.443 1.245-.224.606-.274 1.263-.144 1.896.13.634.433 1.218.877 1.688.47.443 1.054.747 1.687.878.633.132 1.29.084 1.897-.136.274.586.705 1.084 1.246 1.439.54.354 1.17.551 1.816.569.647-.016 1.276-.213 1.817-.567s.972-.854 1.245-1.44c.604.239 1.266.296 1.903.164.636-.132 1.22-.447 1.68-.907.46-.46.776-1.044.908-1.681s.075-1.299-.165-1.903c.586-.274 1.084-.705 1.439-1.246.354-.54.551-1.17.569-1.816zM9.662 14.85l-3.429-3.428 1.293-1.302 2.072 2.072 4.4-4.794 1.347 1.246z"></path></g></svg></span>
                    </div>
                  </div>
                </a></div>
              </div>
<!--              <div class="css-175oi2r r-18u37iz r-1wbh5a2 r-1ez5h0i">-->
<!--                <div class="css-175oi2r r-1d09ksm r-18u37iz r-1wbh5a2">-->
<!--                  <div class="css-175oi2r r-1wbh5a2 r-dnmrzs"><a href="/aheze0" role="link" tabindex="-1"-->
<!--                                                                 class="css-175oi2r r-1wbh5a2 r-dnmrzs r-1ny4l3l r-1loqt21">-->
<!--                    <div dir="ltr"-->
<!--                         class="css-146c3p1 r-dnmrzs r-1udh08x r-3s2u2q r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-18u37iz r-1wvb978"-->
<!--                         style="text-overflow: unset; color: rgb(83, 100, 113);"><span-->
<!--                        class="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3"-->
<!--                        style="text-overflow: unset;">@aheze0</span></div>-->
<!--                  </a></div>-->
<!--                  <div dir="ltr" aria-hidden="true"-->
<!--                       class="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-1q142lx r-n7gxbd"-->
<!--                       style="text-overflow: unset; color: rgb(83, 100, 113);"><span-->
<!--                      class="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3" style="text-overflow: unset;">·</span>-->
<!--                  </div>-->
<!--                  <div class="css-175oi2r r-18u37iz r-1q142lx"><a href="/aheze0/status/1813483966751805483" dir="ltr"-->
<!--                                                                  aria-label="1 hour ago" role="link"-->
<!--                                                                  class="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-xoduu5 r-1q142lx r-1w6e6rj r-9aw3ui r-3s2u2q r-1loqt21"-->
<!--                                                                  style="text-overflow: unset; color: rgb(83, 100, 113);">-->
<!--                    <time datetime="2024-07-17T08:00:45.000Z">1h</time>-->
<!--                  </a></div>-->
<!--                </div>-->
<!--              </div>-->
            </div>
          </div>
        </div>
        <div class="css-175oi2r r-1kkk96v">
          <div class="css-175oi2r r-1awozwy r-18u37iz r-1cmwbt1 r-1wtj0ep">
            <div class="css-175oi2r r-1awozwy r-6koalj r-18u37iz">
              <div class="css-175oi2r">
                <div class="css-175oi2r r-18u37iz r-1h0z5md">
                  <button aria-expanded="false" aria-haspopup="menu" aria-label="More" role="button"
                          class="css-175oi2r r-1777fci r-bt1l66 r-bztko3 r-lrvibr r-1loqt21 r-1ny4l3l"
                          data-testid="caret" type="button">
                    <div dir="ltr"
                         class="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-1awozwy r-6koalj r-1h0z5md r-o7ynqc r-clp7b1 r-3s2u2q"
                         style="text-overflow: unset; color: rgb(83, 100, 113);">
                      <div class="css-175oi2r r-xoduu5">
                        <div
                            class="css-175oi2r r-xoduu5 r-1p0dtai r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-1niwhzg r-sdzlij r-xf4iuw r-o7ynqc r-6416eg r-1ny4l3l"></div>
                        <svg viewBox="0 0 24 24" aria-hidden="true"
                             class="r-4qtqp9 r-yyyyoo r-dnmrzs r-bnwqim r-lrvibr r-m6rgpd r-1xvli5t r-1hdv0qi">
                          <g>
                            <path
                                d="M3 12c0-1.1.9-2 2-2s2 .9 2 2-.9 2-2 2-2-.9-2-2zm9 2c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm7 0c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2z"></path>
                          </g>
                        </svg>
                      </div>
                    </div>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="css-175oi2r">
      <div dir="auto" lang="en"
           class="css-146c3p1 r-8akbws r-krxsd3 r-dnmrzs r-1udh08x r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-bnwqim"
           id="id__ve9cyjuwti" data-testid="tweetText"
           style="-webkit-line-clamp: 10; text-overflow: unset; color: rgb(15, 20, 25);"><span
          class="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3" style="text-overflow: unset;">就你会刷 Twitter ？</span>
      </div>
    </div>
<!--    <div aria-labelledby="id__rqgdvu4q8gt id__gl3jykob3lq" class="css-175oi2r r-9aw3ui r-1s2bzr4"-->
<!--         id="id__n35q5djjqmc">-->
<!--      <div class="css-175oi2r r-9aw3ui">-->
<!--        <div class="css-175oi2r">-->
<!--          <div class="css-175oi2r">-->
<!--            <div class="css-175oi2r r-1ets6dv r-1phboty r-rs99b7 r-1867qdf r-1udh08x r-o7ynqc r-6416eg r-1ny4l3l">-->
<!--              <div class="css-175oi2r">-->
<!--                <div class="css-175oi2r r-1pi2tsx" data-testid="tweetPhoto">-->
<!--                  <div class="css-175oi2r" style="visibility: hidden;">-->
<!--                    <div class="css-175oi2r r-1adg3ll r-1udh08x">-->
<!--                      <div class="r-1adg3ll r-13qz1uu" style="padding-bottom: 78.835%;"></div>-->
<!--                      <div class="r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-ipm5af r-13qz1uu">-->
<!--                        <div class="css-175oi2r r-1awozwy r-16y2uox r-1pi2tsx r-1777fci r-dd0y9b r-3o4zer">-->
<!--                          <div role="progressbar" aria-valuemax="1" aria-valuemin="0"-->
<!--                               class="css-175oi2r r-1awozwy r-1777fci">-->
<!--                            <div class="css-175oi2r r-17bb2tj r-1muvv40 r-1yef0xd r-1ldzwu0"-->
<!--                                 style="height: 26px; width: 26px;">-->
<!--                              <svg height="100%" viewBox="0 0 32 32" width="100%">-->
<!--                                <circle cx="16" cy="16" fill="none" r="14" stroke-width="4"-->
<!--                                        style="stroke: rgb(29, 155, 240); opacity: 0.2;"></circle>-->
<!--                                <circle cx="16" cy="16" fill="none" r="14" stroke-width="4"-->
<!--                                        style="stroke: rgb(29, 155, 240); stroke-dasharray: 80; stroke-dashoffset: 60;"></circle>-->
<!--                              </svg>-->
<!--                            </div>-->
<!--                          </div>-->
<!--                        </div>-->
<!--                      </div>-->
<!--                    </div>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
    <div class="css-175oi2r">
      <div class="css-175oi2r">
<!--        <div aria-label="14 replies, 9 reposts, 281 likes, Liked, 63 bookmarks, 8472 views" role="group"-->
<!--             class="css-175oi2r r-1kbdv8c r-18u37iz r-1wtj0ep r-1ye8kvj r-1s2bzr4" id="id__sk0q04ghf1k">-->
<!--          <div class="css-175oi2r r-18u37iz r-1h0z5md r-13awgt0">-->
<!--            <button aria-label="14 Replies. Reply" role="button"-->
<!--                    class="css-175oi2r r-1777fci r-bt1l66 r-bztko3 r-lrvibr r-1loqt21 r-1ny4l3l" data-testid="reply"-->
<!--                    type="button">-->
<!--              <div dir="ltr"-->
<!--                   class="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-1awozwy r-6koalj r-1h0z5md r-o7ynqc r-clp7b1 r-3s2u2q"-->
<!--                   style="text-overflow: unset; color: rgb(83, 100, 113);">-->
<!--                <div class="css-175oi2r r-xoduu5">-->
<!--                  <div-->
<!--                      class="css-175oi2r r-xoduu5 r-1p0dtai r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-1niwhzg r-sdzlij r-xf4iuw r-o7ynqc r-6416eg r-1ny4l3l"></div>-->
<!--                  <svg viewBox="0 0 24 24" aria-hidden="true"-->
<!--                       class="r-4qtqp9 r-yyyyoo r-dnmrzs r-bnwqim r-lrvibr r-m6rgpd r-1xvli5t r-1hdv0qi">-->
<!--                    <g>-->
<!--                      <path-->
<!--                          d="M1.751 10c0-4.42 3.584-8 8.005-8h4.366c4.49 0 8.129 3.64 8.129 8.13 0 2.96-1.607 5.68-4.196 7.11l-8.054 4.46v-3.69h-.067c-4.49.1-8.183-3.51-8.183-8.01zm8.005-6c-3.317 0-6.005 2.69-6.005 6 0 3.37 2.77 6.08 6.138 6.01l.351-.01h1.761v2.3l5.087-2.81c1.951-1.08 3.163-3.13 3.163-5.36 0-3.39-2.744-6.13-6.129-6.13H9.756z"></path>-->
<!--                    </g>-->
<!--                  </svg>-->
<!--                </div>-->
<!--                <div class="css-175oi2r r-xoduu5 r-1udh08x"><span data-testid="app-text-transition-container"-->
<!--                                                                  style="transition-property: transform; transition-duration: 0.3s; transform: translate3d(0px, 0px, 0px);"><span-->
<!--                    class="css-1jxf684 r-1ttztb7 r-qvutc0 r-poiln3 r-n6v787 r-1cwl3u0 r-1k6nrdp r-n7gxbd"-->
<!--                    style="text-overflow: unset;"><span class="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3"-->
<!--                                                        style="text-overflow: unset;">14</span></span></span></div>-->
<!--              </div>-->
<!--            </button>-->
<!--          </div>-->
<!--          <div class="css-175oi2r r-18u37iz r-1h0z5md r-13awgt0">-->
<!--            <button aria-expanded="false" aria-haspopup="menu" aria-label="9 reposts. Repost" role="button"-->
<!--                    class="css-175oi2r r-1777fci r-bt1l66 r-bztko3 r-lrvibr r-1loqt21 r-1ny4l3l" data-testid="retweet"-->
<!--                    type="button">-->
<!--              <div dir="ltr"-->
<!--                   class="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-1awozwy r-6koalj r-1h0z5md r-o7ynqc r-clp7b1 r-3s2u2q"-->
<!--                   style="text-overflow: unset; color: rgb(83, 100, 113);">-->
<!--                <div class="css-175oi2r r-xoduu5">-->
<!--                  <div-->
<!--                      class="css-175oi2r r-xoduu5 r-1p0dtai r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-1niwhzg r-sdzlij r-xf4iuw r-o7ynqc r-6416eg r-1ny4l3l"></div>-->
<!--                  <svg viewBox="0 0 24 24" aria-hidden="true"-->
<!--                       class="r-4qtqp9 r-yyyyoo r-dnmrzs r-bnwqim r-lrvibr r-m6rgpd r-1xvli5t r-1hdv0qi">-->
<!--                    <g>-->
<!--                      <path-->
<!--                          d="M4.5 3.88l4.432 4.14-1.364 1.46L5.5 7.55V16c0 1.1.896 2 2 2H13v2H7.5c-2.209 0-4-1.79-4-4V7.55L1.432 9.48.068 8.02 4.5 3.88zM16.5 6H11V4h5.5c2.209 0 4 1.79 4 4v8.45l2.068-1.93 1.364 1.46-4.432 4.14-4.432-4.14 1.364-1.46 2.068 1.93V8c0-1.1-.896-2-2-2z"></path>-->
<!--                    </g>-->
<!--                  </svg>-->
<!--                </div>-->
<!--                <div class="css-175oi2r r-xoduu5 r-1udh08x"><span data-testid="app-text-transition-container"-->
<!--                                                                  style="transition-property: transform; transition-duration: 0.3s; transform: translate3d(0px, 0px, 0px);"><span-->
<!--                    class="css-1jxf684 r-1ttztb7 r-qvutc0 r-poiln3 r-n6v787 r-1cwl3u0 r-1k6nrdp r-n7gxbd"-->
<!--                    style="text-overflow: unset;"><span class="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3"-->
<!--                                                        style="text-overflow: unset;">9</span></span></span></div>-->
<!--              </div>-->
<!--            </button>-->
<!--          </div>-->
<!--          <div class="css-175oi2r r-18u37iz r-1h0z5md r-13awgt0">-->
<!--            <button aria-label="281 Likes. Liked" role="button"-->
<!--                    class="css-175oi2r r-1777fci r-bt1l66 r-bztko3 r-lrvibr r-1loqt21 r-1ny4l3l" data-testid="unlike"-->
<!--                    type="button">-->
<!--              <div dir="ltr"-->
<!--                   class="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-1awozwy r-6koalj r-1h0z5md r-o7ynqc r-clp7b1 r-3s2u2q"-->
<!--                   style="text-overflow: unset; color: rgb(249, 24, 128);">-->
<!--                <div class="css-175oi2r r-xoduu5">-->
<!--                  <div-->
<!--                      class="css-175oi2r r-xoduu5 r-1p0dtai r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-1niwhzg r-sdzlij r-xf4iuw r-o7ynqc r-6416eg r-1ny4l3l"></div>-->
<!--                  <svg viewBox="0 0 24 24" aria-hidden="true"-->
<!--                       class="r-4qtqp9 r-yyyyoo r-dnmrzs r-bnwqim r-lrvibr r-m6rgpd r-1xvli5t r-1hdv0qi">-->
<!--                    <g>-->
<!--                      <path-->
<!--                          d="M20.884 13.19c-1.351 2.48-4.001 5.12-8.379 7.67l-.503.3-.504-.3c-4.379-2.55-7.029-5.19-8.382-7.67-1.36-2.5-1.41-4.86-.514-6.67.887-1.79 2.647-2.91 4.601-3.01 1.651-.09 3.368.56 4.798 2.01 1.429-1.45 3.146-2.1 4.796-2.01 1.954.1 3.714 1.22 4.601 3.01.896 1.81.846 4.17-.514 6.67z"></path>-->
<!--                    </g>-->
<!--                  </svg>-->
<!--                </div>-->
<!--                <div class="css-175oi2r r-xoduu5 r-1udh08x"><span data-testid="app-text-transition-container"-->
<!--                                                                  style="transition-property: transform; transition-duration: 0.3s; transform: translate3d(0px, 0px, 0px);"><span-->
<!--                    class="css-1jxf684 r-1ttztb7 r-qvutc0 r-poiln3 r-n6v787 r-1cwl3u0 r-1k6nrdp r-n7gxbd"-->
<!--                    style="text-overflow: unset;"><span class="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3"-->
<!--                                                        style="text-overflow: unset;">281</span></span></span></div>-->
<!--              </div>-->
<!--            </button>-->
<!--          </div>-->
<!--          <div class="css-175oi2r r-18u37iz r-1h0z5md r-13awgt0"><a-->
<!--              href="/aheze0/status/1813483966751805483/analytics" aria-label="8472 views. View post analytics"-->
<!--              role="link" class="css-175oi2r r-1777fci r-bt1l66 r-bztko3 r-lrvibr r-1ny4l3l r-1loqt21">-->
<!--            <div dir="ltr"-->
<!--                 class="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-1awozwy r-6koalj r-1h0z5md r-o7ynqc r-clp7b1 r-3s2u2q"-->
<!--                 style="text-overflow: unset; color: rgb(83, 100, 113);">-->
<!--              <div class="css-175oi2r r-xoduu5">-->
<!--                <div-->
<!--                    class="css-175oi2r r-xoduu5 r-1p0dtai r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-1niwhzg r-sdzlij r-xf4iuw r-o7ynqc r-6416eg r-1ny4l3l"></div>-->
<!--                <svg viewBox="0 0 24 24" aria-hidden="true"-->
<!--                     class="r-4qtqp9 r-yyyyoo r-dnmrzs r-bnwqim r-lrvibr r-m6rgpd r-1xvli5t r-1hdv0qi">-->
<!--                  <g>-->
<!--                    <path d="M8.75 21V3h2v18h-2zM18 21V8.5h2V21h-2zM4 21l.004-10h2L6 21H4zm9.248 0v-7h2v7h-2z"></path>-->
<!--                  </g>-->
<!--                </svg>-->
<!--              </div>-->
<!--              <div class="css-175oi2r r-xoduu5 r-1udh08x"><span data-testid="app-text-transition-container"-->
<!--                                                                style="transition-property: transform; transition-duration: 0.3s; transform: translate3d(0px, 0px, 0px);"><span-->
<!--                  class="css-1jxf684 r-1ttztb7 r-qvutc0 r-poiln3 r-n6v787 r-1cwl3u0 r-1k6nrdp r-n7gxbd"-->
<!--                  style="text-overflow: unset;"><span class="css-1jxf684 r-bcqeeo r-1ttztb7 r-qvutc0 r-poiln3"-->
<!--                                                      style="text-overflow: unset;">8.4K</span></span></span></div>-->
<!--            </div>-->
<!--          </a></div>-->
<!--          <div class="css-175oi2r"-->
<!--               style="justify-content: inherit; display: inline-grid; transform: rotate(0deg) scale(1) translate3d(0px, 0px, 0px);">-->
<!--            <div class="css-175oi2r r-18u37iz r-1h0z5md">-->
<!--              <button aria-expanded="false" aria-haspopup="menu" aria-label="Share post" role="button"-->
<!--                      class="css-175oi2r r-1777fci r-bt1l66 r-bztko3 r-lrvibr r-1loqt21 r-1ny4l3l" type="button">-->
<!--                <div dir="ltr"-->
<!--                     class="css-146c3p1 r-bcqeeo r-1ttztb7 r-qvutc0 r-37j5jr r-a023e6 r-rjixqe r-16dba41 r-1awozwy r-6koalj r-1h0z5md r-o7ynqc r-clp7b1 r-3s2u2q"-->
<!--                     style="text-overflow: unset; color: rgb(83, 100, 113);">-->
<!--                  <div class="css-175oi2r r-xoduu5">-->
<!--                    <div-->
<!--                        class="css-175oi2r r-xoduu5 r-1p0dtai r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-1niwhzg r-sdzlij r-xf4iuw r-o7ynqc r-6416eg r-1ny4l3l"></div>-->
<!--                    <svg viewBox="0 0 24 24" aria-hidden="true"-->
<!--                         class="r-4qtqp9 r-yyyyoo r-dnmrzs r-bnwqim r-lrvibr r-m6rgpd r-1xvli5t r-1hdv0qi">-->
<!--                      <g>-->
<!--                        <path-->
<!--                            d="M12 2.59l5.7 5.7-1.41 1.42L13 6.41V16h-2V6.41l-3.3 3.3-1.41-1.42L12 2.59zM21 15l-.02 3.51c0 1.38-1.12 2.49-2.5 2.49H5.5C4.11 21 3 19.88 3 18.5V15h2v3.5c0 .28.22.5.5.5h12.98c.28 0 .5-.22.5-.5L19 15h2z"></path>-->
<!--                      </g>-->
<!--                    </svg>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </button>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
      </div>
    </div>
  </div>
</template>

<style scoped>

</style>
